### PR TITLE
Add multiarch image build

### LINKED ISSUE #15: Multi-arch images
It would be nice to have multi-arch images of the visualizer available.

We noticed that currently the image is only build for amd64.

(Here's how we build & (further down) push multi-arch images in Cluster API: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L655)

### PR DESCRIPTION
**Pull request by Jont828**
Fixes #15

### CODE REVIEW

**Comment by Jont828** [comment]
@sbueringer I set up some changes to build a single multiarch image, is this what you were looking for? On the [latest tag](https://github.com/Jont828/cluster-api-visualizer/pkgs/container/cluster-api-visualizer/56757401?tag=latest) we can see that it has the different architectures available.

**Comment by sbueringer** [comment]
Nice, looks perfect!!

@killianmuldoon Maybe if you have some time and if you remember. Can you verify if it works correctly? (I remember we did one loop before KubeCon to build our own multi-arch and you verified it afterwards)

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Latest image from the repo is mult-arch and I'm able to successfully run it on amd64 and arm64.

Thanks!

**Comment by Jont828** [comment]
Thanks for testing this out! Will go ahead and merge!

**Pull request merged**
